
Import('env')
Import('atlas_link_libs')
Import('tcmalloc_link_libs')

env.Program('gaussian.cpp')
env.Program('svm_regression.cpp', LIBS=atlas_link_libs )
#env.Program('svm_ranking.cpp', LIBS=atlas_link_libs )
env.Program('svm_classification.cpp', LIBS=tcmalloc_link_libs)
