
Import('env')
Import('install_dir')

kml_path = 'research/kml/'

obj = []
obj += env.HTML( 'index.tex' )
obj += env.HTML( 'installation.tex' )


env.Install( install_dir + '/research/kml/', 'install_WinNT_VC.html' )

env.Install( install_dir + '/' + kml_path, [ 
	'boost_bindings.tar.gz', 
	'boost_bindings.zip', 
	'kml-0.1.tar.gz', 
	'kml-0.1.zip',
	'WinNT_PIIISSE1.zip',
	'WinNT_ATHLONSSE1.zip',
	'kml_win_dll.sh'
	] )

for loc in ['documentation']:
	o = SConscript( dirs= loc )
	obj += o


Return( 'obj' )

