
Import('env')
Import('install_dir')

kmlroot = '/research/kml'

obj = []

# generic pages
obj += env.XHTML( 'index.html_fase4' )
obj += env.HTML(  'improve.tex' )
obj += env.HTML(  'tutorial.tex' )
obj += env.HTML(  'installation.tex' )

# process subdirectories
for loc in ['reference']:
	o = SConscript( dirs= loc )
	obj += o

env.Install( install_dir + '/research/kml', 
	['boost_bindings.tar.gz',
	 'boost_bindings.zip',
	 'kml-0.1.tar.gz',
	 'kml-0.1.zip',
	 'kml_win_dll.sh',
	 'WinNT_ATHLONSSE1.zip',
	 'WinNT_PIIISSE1.zip',
         'install_WinNT_VC.html'] )


Return( 'obj' )

